### ISSUE TITLE
[RELEASE] DS Software ULS v1.2.0 Tremendous Update

### ISSUE THREAD

**Issue by DSSoftware** [DS-Software/ULS#31]
# Checklist
### Features:
- [x] Add consent form in external_auth (#21)
- [x] Add more user data fields (#12)
- [x] Standardize Access Tokens (#27)
- [x] Fault redirect in external_auth (#24)
- [x] Add a QR Scanner to scan EasyLogin QRs (#25)
- [ - ] Add CAPTCHA to ULS (#22)
- [x] Add a spam email filter (e785e2d1e502ecc2686da0e7c618f8cc2d1bbe15)
- [x] Now external_auth doesn't redirect users, everything happens in the iframe. (#33)

### Bugfixes:
- [x] Updated EMail Templates (#15)
- [x] Some GUI Changes (#29)
- [x] Big top margin (#30)
- [x] regenerateProjectPublic & regenerateProjectSecret of DB are missing 2 arguments (7be6cc8ca90c0090f4498143645c10ae0309823d)
- [x] Impossible to create new scopes' description or title (e22c915beb60370096e0946f734bd94aaac0b4e3)

## Documentation
- [x] Create an example of project integration (#17)

**Comment by DSSoftware** [comment]
Adding CAPTCHA makes a new dependency, for now, it might seriously impact performance and complicate the installation process. Moreover, it means that there will be no backwards compatibility. So, feature #22 will be released in next releases.

**Comment by DSSoftware** [comment]
Alr, DS Software ULS v1.2.0 is ready for release, I guess. Nevertheless, it needs some testing.
Coming soon.
