### ISSUE TITLE
[RELEASE] DS Software ULS v1.3.0 Epic Update

### ISSUE THREAD

**Issue by DSSoftware** [DS-Software/ULS#35]
# Checklist
### Features:
- [x] Rework sessions and session check (#32)
- [x] Rework password authentication, as it's really easy to forge it now.
- [x] Add CAPTCHA to ULS (#22)
- [x] Changed Alertify's styles to look better
- [x] Reformatted API and DB
- [x] Add DB that contains all failed attempts for some time to prevent bruteforcing, to users that are blocked by that - show captcha.
- [x] Added color themes
- [x] Revamped GUI
- [x] Added admin panel

### Bugfixes:
- [x] Standardize functions' and methods' names (#36)
- [x] API Line 255 was $session_id == $session_id
- [x] API Line 349 was $session_id == $session_id
- [x] In some places it was missing user's login or user info, as it was pointing to undefined variables
- [x] Fixed some issues with 2FA and EMail verification
- [x] Made some performance enhancements
- [x] Updated example config and database setup

## Documentation
- [x] Create API Documentation (#34)

**Comment by DSSoftware** [comment]
Ill just add some features for admins, but that's all for now. Release soon I hope.
